remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Example Axis Integration Projects
description: Learn how to create simple integration projects using Axis devices, MQTT, NodeRED, IoT, Camera as a sensor, System Integration
